<?php
/**
 * SqualoMail_SqmMcMagentoTwo Magento JS component
 *
 * @category    SqualoMail
 * @package     SqualoMail_SqmMcMagentoTwo
 * @author      Ebizmarts Team <info@ebizmarts.com>
 * @copyright   Ebizmarts (http://ebizmarts.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="configmonkey_apikey" class="admin__page-section-item" style="display:none;"
     data-mage-init='{"configmonkeyapikey":{
     "storeUrl": "<?php echo $this->getUrl('sqmmc/stores/get');?>",
     "detailsUrl": "<?php echo $this->getUrl('sqmmc/ecommerce/getaccountdetails');?>",
     "storeGridUrl": "<?php echo $this->getUrl('sqmmc/stores/index');?>",
     "createWebhookUrl": "<?php echo $this->getUrl('sqmmc/ecommerce/createWebhook');?>",
     "getInterestUrl": "<?php echo $this->getUrl('sqmmc/ecommerce/getInterest');?>",
     "resyncSubscribersUrl": "<?php echo $this->getUrl('sqmmc/ecommerce/resyncSubscribers');?>"}}'>
</div>
<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
    <h4>
        <img width="224px" style="padding-left: 15px;" height="60px" src="https://ebizmarts-website.s3.amazonaws.com/Logo_Ebizmarts.png"/><br><br>
        <div style="padding-left: 15px;">
            <p> <strong style="color:#EA7601;"><?php echo __('SqualoMail v') ?><?php echo $this->getModuleVersion() ?><?php echo __(' by') ?></strong> <a target="_blank" href="http://www.squalomail.com"><strong>SqualoMail</strong></a></p>
            <?php if (!$this->getHasApiKey() ) : ?>
                <p><a style="padding-top: 5px;padding-bottom:5px;padding-left: 30px;padding-right: 30px;background-color:#D75F07 ;color:white;font-weight: bold" href="https://www.squalomail.com" target="_blank">Support SqualoMail4Magento, Subscribe for a free SqualoMail Account!</a> </p>
            <?php endif; ?>
        </div>
    </h4>
</div>