<?php
/**
 * SqualoMail_SqmMcMagentoTwo Magento JS component
 *
 * @category    SqualoMail
 * @package     SqualoMail_SqmMcMagentoTwo
 * @author      Ebizmarts Team <info@ebizmarts.com>
 * @copyright   Ebizmarts (http://ebizmarts.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="configmonkey_apikey" class="admin__page-section-item" style="display:none;"
     data-mage-init='{"configmonkeyapikey":{
     "storeUrl": "<?php echo $this->getUrl('sqmmc/stores/get');?>",
     "detailsUrl": "<?php echo $this->getUrl('sqmmc/ecommerce/getaccountdetails');?>",
     "storeGridUrl": "<?php echo $this->getUrl('sqmmc/stores/index');?>",
     "createWebhookUrl": "<?php echo $this->getUrl('sqmmc/ecommerce/createWebhook');?>",
     "getInterestUrl": "<?php echo $this->getUrl('sqmmc/ecommerce/getInterest');?>",
     "resyncProductsUrl": "<?php echo $this->getUrl('mailchimp/ecommerce/resyncProducts');?>",
     "scope": "<?php echo $this->getScope();?>",
     "scopeId": "<?php echo $this->getScopeId(); ?>"
    }}'>
</div>
<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
    <h4>
        <div style="padding-left: 15px;">
            <p>
                <strong style="color:#EA7601;">
                    <?php echo __('SqualoMail v') ?><?php echo $this->getModuleVersion() ?><?php echo __(' by') ?>
                </strong>
                <a target="_blank" href="http://www.squalomail.com"><strong>SqualoMail</strong></a>
            </p>
        </div>
    </h4>
</div>